name = "ParallelMapReduce"
uuid = "35c9ef8c-44cb-42a7-bccd-f3b9e73321fd"
authors = ["Hakan Carlsson <hakan.carlsson@gmail.com>"]
version = "0.0.3"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"


[compat]
julia = "1.4"
